### ISSUE TITLE
Support kubernetes auth backend for vault

### ISSUE THREAD

**Issue by praxist** [reddit/baseplate#132]
From my understanding, we currently only authenticate to vault using the EC2 instance identity document. For the future when we run applications on kubernetes, this will not be sufficient as many arbitrary applications may run on the same instance in different pods.

The kubernetes auth backend is used by providing the role and a JWT mounted within kubernetes pods at `/run/secrets/kubernetes.io/serviceaccount/token` which is used to authenticate as a service account. Therefore, we simply just need to read the contents of this file and authenticate at a designated mount point for the kubernetes auth backend in order to get this working. 

Here is some sample code using the hvac library:
```
import hvac

TOKEN_FILE = '/run/secrets/kubernetes.io/serviceaccount/token'
VAULT_URL = 'xxxx' 
AUTH_ENDPOINT = '/v1/auth/kubernetes/login'

with open(TOKEN_FILE, 'r') as f:
    token = f.read()

role = 'xxxx'

params = {
  'jwt': token,
  'role': role
}

client = hvac.Client(url=VAULT_URL)
client.auth(AUTH_ENDPOINT, json=params)
```

I'm still getting familiar with the code, but it seems we may want to build this functionality into [VaultClientFactory](https://github.com/reddit/baseplate/blob/master/baseplate/secrets/fetcher.py#L117) rather than use hvac for more flexibility.

**Comment by praxist** [comment]
👓  @spladug @gtaylor

**Comment by gtaylor** [comment]
Will `AUTH_ENDPOINT` always be static, or would it differ if there are multiple Kubernetes auth backends set up on Vault?

IE: '/v1/auth/kubernetes/some-cluster/login'

**Comment by praxist** [comment]
Just as you said - the auth endpoint will change if the vault backend is mounted elsewhere, like in the example of having multiple clusters.

**Comment by gtaylor** [comment]
This all makes sense to me. I don't have a ton of useful advice on the baseplate implementation side, but Andrew Boyle and Adam Collins over on Platform have used the current baseplate+Vault setup enough to potentially have some opinions until Neil gets back.

**Comment by spladug** [comment]
72ba4b023553fd7e71eb1173f3aeeb88b3a2981f
