### ISSUE TITLE
Document or include Sphinx requirements

### ISSUE THREAD

**Issue by gtaylor** [reddit/baseplate#16]
I needed to install the following to get the docs to build locally:

* sphinx
* sphinxcontrib-spelling
* pyenchant

I have traditionally followed the `docs-requirements.txt`/`dev-requirements.txt` pattern for stuff like this, but didn't want to presume this is where you were heading with a premature PR.

I can toss a PR over the fence if you let me know how you'd like to handle it (or not handle it).

Looking good so far!

**Comment by spladug** [comment]
Thanks for the feedback. I've been pretty lax on the requirements stuff because I personally tend to use `apt-get` for these kinds of dependencies. I'll try and clean up the build/install process shortly.

**Comment by spladug** [comment]
Fixed in 2f8cd145606f515ce1e1d5d8a465f0b5bf2bbc3f
