### ISSUE TITLE
Better logging level control for third-party dependencies

### ISSUE THREAD

**Issue by snoost** [reddit/baseplate#170]
Baseplate uses a few third-party libraries such as python cassandra driver. Their log lines are rather chatty, making backend logs very noisy.

Would be good if baseplate provides a idiomatic way for services to tweak the log levels, since baseplate is aware of all the libraries it depends on.

**Comment by spladug** [comment]
Python's standard library already does this and baseplate honors it: http://baseplate.readthedocs.io/en/stable/cli/serve.html#logging

If you want to override specific loggers, just add the relevant config to your application's INI file and you're good to go.
