### ISSUE TITLE
Cannot raise Thrift exceptions in Python 3

### ISSUE THREAD

**Issue by pacejackson** [reddit/baseplate#184]
`BaseplateProcessorEventHandler. handlerError` uses `logger.exception` which throws an error whenever you raise a Thrift exception in Python 3 since the generated Thrift exceptions are unhashable.

https://github.com/reddit/baseplate/blob/69eba73ad7493e8c4822677b391346b5a8ee7c38/baseplate/integration/thrift/__init__.py#L117

This means that we cannot raise Thrift exceptions within a Python 3 Thrift service without monkey patching `TException` to include the methods that we need.

**Comment by spladug** [comment]
We should fix Thrift.
