### ISSUE TITLE
Quiet cassandra log spam

### ISSUE THREAD

**Issue by manishapme** [reddit/baseplate#189]
The python-driver for cassandra can be very noisy in the logs. Lots of messages like
```
Jul  3 10:29:05 host [service] 23701:MainThread:cassandra.policies:INFO:Using datacenter 'ue1' for DCAwareRoundRobinPolicy (via host '10.0.0.0); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes#015
```

This comes from the `on_up` method as found here https://datastax.github.io/python-driver/_modules/cassandra/policies.html

I believe we could reduce this by optionally passing in `load_balancing_policy` here: https://github.com/reddit/baseplate/blob/master/baseplate/context/cassandra.py#L14

`load_balancing_policy=DCAwareRoundRobinPolicy(local_dc=local_dc)`

**Comment by spladug** [comment]
Does anything need to change in Baseplate for this? Applications will know best how their own databases are set up and it looks like they can pass that info through in the `**kwargs` there?
