### ISSUE TITLE
Edge context didn't show up after upgrading to 0.28

### ISSUE THREAD

**Issue by spladug** [reddit/baseplate#222]
We upgraded a service to 0.28 and found that edge request context (particularly a service auth token) was not getting added to the context anymore. Reverting back to 0.27 resolved the issue.

I suspect 46db4cd60d8aebbe7c25ea1a7343dbea3f8fdbf1 didn't find trace headers for some reason and then edge context was lost as a result (which would be fixed with 7a19ee84242bb5d3f04414f717bef466a76adec5 -- but this is still an issue).

**Comment by spladug** [comment]
Confirmed 46db4cd60d8aebbe7c25ea1a7343dbea3f8fdbf1. Likely culprit (props to Courtney) is that we're strictly requiring _all_ the trace headers (including the optional ones `Flags` and `Sampled`) to accept any of them. This is a bug since even our own client will only send those optional headers whe non-null.

**Comment by dkasper** [comment]
That's good to know since I discovered this while writing the tests for #216

**Comment by spladug** [comment]
Fixed in ea92fb2b29415db58f03be54e6af2b6582a237b3
