### ISSUE TITLE
config.Optional always returns the default for Boolean values

### ISSUE THREAD

**Issue by bsimpson63** [reddit/baseplate#83]
https://github.com/reddit/baseplate/blob/master/baseplate/config.py#L307

If the value from the config is `False` this check is falsy and the default will be returned.

**Comment by spladug** [comment]
That check is working on the raw string, not the already-parsed version, so truthiness should just be if the string is empty or not. AFAICT this does work as intended with booleans:

```python
>>> Optional(Boolean, default=None)("")
>>> Optional(Boolean, default=None)("True")
True
>>> Optional(Boolean, default=None)("False")
False
```

Do you have an example of it failing?

**Comment by bsimpson63** [comment]
Arg. I was accidentally editing files in the debian directory so the config changes I expected weren't happening. Sorry for the false alarm.
